<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NetworkConnection.ConnectionType</name>
   <tag></tag>
   <elementGuidId>103212cb-dda2-49e6-bdc1-4870b8133835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.mobile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'NetworkConnection.ConnectionType')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c891e9be-32ae-4bec-9f4a-0df53cc8fce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../mobile/NetworkConnection.ConnectionType.html</value>
      <webElementGuid>c763dd4c-6ce7-4cf5-8b20-602f7968d84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.mobile</value>
      <webElementGuid>a2215ca4-b5ac-4bc7-be68-57389ebed3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NetworkConnection.ConnectionType</value>
      <webElementGuid>d6e5249b-dee2-4642-889e-78cd18f6d4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;summary&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/section[1]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/code[1]/a[1]</value>
      <webElementGuid>97f81c42-8374-4721-a34d-572c87e3a552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ChromeDriver/iframe_classFrame</value>
      <webElementGuid>88ff2eb4-c7ab-4b87-afb9-2078a27c83de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NetworkConnection.ConnectionType')]</value>
      <webElementGuid>46ad744d-918c-4a07-b5dc-85e8f8dab6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NetworkConnection'])[2]/following::a[1]</value>
      <webElementGuid>220374e3-92ff-4723-9a91-359c2fadb6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver'])[3]/preceding::a[2]</value>
      <webElementGuid>573c8224-7ce5-4bb4-96e7-55e402183b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NetworkConnection.ConnectionType']/parent::*</value>
      <webElementGuid>4375f9d4-ed98-46d6-ab8a-b9f8d7a4d3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../mobile/NetworkConnection.ConnectionType.html')]</value>
      <webElementGuid>f9bbf954-7fa9-4717-ab6a-d7676bb832c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/code/a</value>
      <webElementGuid>05fc4ef3-b8ca-4e11-b661-afd65e3a4990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../mobile/NetworkConnection.ConnectionType.html' and @title = 'class in org.openqa.selenium.mobile' and (text() = 'NetworkConnection.ConnectionType' or . = 'NetworkConnection.ConnectionType')]</value>
      <webElementGuid>5611cb09-aab1-4b20-8873-0dc35cdaa7b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
