<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>1300ccb4-d81b-44c9-95b6-2b03cbc41f37</testSuiteGuid>
   <testCaseLink>
      <guid>193d1454-04ca-48b1-9121-73e312ffe118</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a3b8092c-bb95-49ca-a2c8-2b445231d575</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a3b8092c-bb95-49ca-a2c8-2b445231d575</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>3c1ab34c-75d7-43f9-8f5a-037d5e622940</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a3b8092c-bb95-49ca-a2c8-2b445231d575</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>8cda881f-8343-40b1-bc17-536435903021</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
