<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Bagikan_u243-playerId__28236204--20_h_6560b7</name>
   <tag></tag>
   <elementGuidId>fa3e4eba-8d9c-4395-8ea2-a712ca89f09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u243-playerId__28236204--20_html5_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='u243-playerId__28236204--20_html5_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>cf9bc75f-6256-4f9c-979f-2afe5c4721e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>6e0e8cf5-bfd8-4e39-8750-ff56e07b6424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u243-playerId__28236204--20_html5_api</value>
      <webElementGuid>2dd286e4-04b3-45a5-93de-67bd1e8b319a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>55331a56-0288-4681-a3a3-fe14f5ab554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>74c471f0-6c22-4bc4-bdbe-6cc9e47f047b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e7d67eeb-1eb8-46e8-aa0f-4c3fce523084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>d0fd589d-bff4-4478-b8f9-d4815540c98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.udemy.com/d0c059ab-1bd2-4cc9-9c21-c1e5352635fc</value>
      <webElementGuid>8fe26bc3-c164-4ac0-b9e4-67568928988f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u243-playerId__28236204--20_html5_api&quot;)</value>
      <webElementGuid>41a24b94-de93-45d4-a537-15ac7abc0667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='u243-playerId__28236204--20_html5_api']</value>
      <webElementGuid>f573d358-575f-4bde-a89b-ee312df4d05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u243-playerId__28236204--20']/video</value>
      <webElementGuid>d1b612d3-52e8-4a86-b220-1f474c495a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>a25f789f-eca8-44de-9869-02f1355769c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'u243-playerId__28236204--20_html5_api' and @src = 'blob:https://www.udemy.com/d0c059ab-1bd2-4cc9-9c21-c1e5352635fc']</value>
      <webElementGuid>8ec6002d-6ffd-4226-8f64-c6d323b12ae0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
