<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_classFrame</name>
   <tag></tag>
   <elementGuidId>02d0609e-a403-40d7-8aa6-2e4c1d8dca4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;classFrame&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='classFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e5797938-892d-4dc4-9daf-59560235d05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-summary.html</value>
      <webElementGuid>d9ff4aaa-0f1d-4e7a-98c4-cf12d123e7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>080f8a7e-4601-4294-9b10-fe47e7af65b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Package, class and interface descriptions</value>
      <webElementGuid>bc48e686-8ec3-4ca0-9ee6-f0b5c01230b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rightIframe</value>
      <webElementGuid>17edec8d-7e05-4396-aeab-04d275129ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;rightContainer&quot;]/iframe[@class=&quot;rightIframe&quot;]</value>
      <webElementGuid>333479fd-3e30-4d91-83a6-b47457e5543f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='classFrame']</value>
      <webElementGuid>cbec80c7-c6bc-4b2e-93ea-aec3928d7210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>1c09d269-f5ac-4dda-acf5-18560b61bbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-summary.html' and @name = 'classFrame' and @title = 'Package, class and interface descriptions']</value>
      <webElementGuid>c2892fc1-b98e-4608-a9f0-4c5f81300b96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
